### ISSUE TITLE
хз баг ли это но... 

### ISSUE THREAD

**Issue by mrksbgg** [xmdnx/exteraGramDesktop#1]
### Steps to reproduce

1. наведитесь на иконку экстеры 
2. ЭКСТЕРАГРАМ???

### Expected behaviour

должно быть exteraGram

### Actual behaviour

пишет Telegram

### Operating system

окна 10

### Version of Telegram Desktop

4.8.4 пререлиз

### Installation source

Other (unofficial) source

### Crash ID

-

**Comment by mrksbgg** [comment]
![image](https://github.com/xmdnx/exteraGramDesktop/assets/101137197/c283faa3-85aa-4eb3-b0fb-d287a9e0056e)
сверху у экстеры

снизу у 64грам (не реклама)
![image](https://github.com/xmdnx/exteraGramDesktop/assets/101137197/2e852ce1-dc41-4979-97d5-691e77254160)

**Comment by xmdnx** [comment]
https://t.me/exteraGramDesktop/58/767

**Comment by xmdnx** [comment]
https://t.me/exteraGramDesktop/58/854 one more
